title: Rbqwow's Blog

tagline: Peace and Love

author:
  name: Rbqwow
  email: admin@rbqwow.link

description:
  What you see is what I want you to see. <br>
  Enjoy yourself and take a good day. <3

url: https://rbqwow.link

minima:
  skin: auto
  date_format: "%F"
  social_links:
    - { platform: bilibili,       user_url: "https://space.bilibili.com/82469063" }
    - { platform: github,         user_url: "https://github.com/rbqwow" }
    - { platform: gitlab,         user_url: "https://gitlab.com/rbqwow" }
    - { platform: telegram,       user_url: "https://t.me/rbqwow" }
    - { platform: twitter,        user_url: "https://twitter.com/rbqwow" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCDlF20IXdd8-ZXZFSakmIWg" }
  disqus:
    shortname: rbqwow

show_excerpts: false

google_analytics: G-XXSWEGK6EX

baseurl: /

remote_theme: jekyll/minima

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
