title: rbqwow.link
author:
  name: Rbqwow
  email: admin@rbqwow.link
description: >
  What you see is what I want you to see.
minima:
  skin: auto
  date_format: "%F"
  social_links:
    - { platform: bilibili,       user_url: "https://space.bilibili.com/82469063" }
    - { platform: github,         user_url: "https://github.com/rbqwow" }
    - { platform: gitlab,         user_url: "https://gitlab.com/rbqwow" }
    - { platform: telegram,       user_url: "https://t.me/rbqwow" }
    - { platform: twitter,        user_url: "https://twitter.com/rbqwow" }
    - { platform: youtube,        user_url: "https://www.youtube.com/channel/UCDlF20IXdd8-ZXZFSakmIWg" }
    - { platform: rss,            user_url: "https://rbqwow.link/feed.xml" }

show_excerpts: true # set to true to show excerpts on the homepage

google_analytics: G-XXSWEGK6EX

# Build settings
baseurl: /
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-seo-tag
